### ISSUE TITLE
Archive collections using their new collection id

### ISSUE THREAD

**Issue by NoisyFlowers** [azgs/azlibrary_database#1]
Currently, we archive collections with a filename based on their old drupal node ids. This will make increasingly less sense as time goes by. Instead, let's archive using the collection's id in the new db. 

This change would mean we have to also change how we discern a new upload from an update to an existing collection. Currently, this is gated by the unique constraint on collections.azgs_path. But if someone tries to update a collection using a directory still carrying the old drupal node id, this gate would not work and the collection would be treated as new. To handle this, we could add a collectionID field in the new json metadata we are defining. If that field is null, we treat it as a new collection. If it contains a value, it is an update. Of course, this introduces a possible avenue for user error...

**Comment by aazaff** [comment]
In terms of human error, we should make the collection_id field of the metadata un-editable by human users. Make it hard-coded to be blank when filling out a new metadata item. If editing an existing item it will load in the collection_id stored in the database.

**Comment by aazaff** [comment]
I've changed my mind about this. Let's get this cleaned up sooner than later.

Let's discuss in our next meeting. We can have @hsnellen help

**Comment by aazaff** [comment]
Once this is done, let's have @hsnellen spot check the urls and metadata etc.

**Comment by NoisyFlowers** [comment]
This has been implemented. 

On dev, there is a db called tmplibrary that is fully populated and includes these changes. It looks good to me but should probably be further compared to the existing azlibrary on that machine. Output products of azlibAdd are in /azlibrary/failures-ddm and /azlibrary/archive-ddm.

There is a problem with old collections 1669 and 1664 sharing the same azgs_old_url. This is not an artifact of these changes. It has been reported elsewhere and is under investigation.

**Comment by aazaff** [comment]
Initial feedback for @NoisyFlowers 

on the following elements of the azgs.json.

1. Null values are handled inconsistently. Sometimes they are stated as `""` or as `null`. It should be handled consistently throughout.
![screenshot 2019-02-18 at 1 06 01 pm](https://user-images.githubusercontent.com/10422595/52974195-f6706380-337d-11e9-8015-8fdc3c62fb71.png)

2. The path extensions do not seem to be populating correctly.
![screenshot 2019-02-18 at 1 07 04 pm](https://user-images.githubusercontent.com/10422595/52974242-1acc4000-337e-11e9-88d9-17f3ba1b43d5.png)

These examples come for collection 791.

**Comment by aazaff** [comment]
Also, might be nice to remove the .DS_Store files from the metadata. That's just silly.

**Comment by hsnellen** [comment]
'tar.gz' that have been checked so far:
66, 208, 290, 361, 460, 587, 720, 802, 887, 929, 968, 1218, 1337.
Opened data in Qgis and projections are all correct.

**Comment by NoisyFlowers** [comment]
I just dropped and rebuilt tmplibrary to incorporate several changes. Can you take another look at a few collections for verification?

**Comment by aazaff** [comment]
@hsnellen is going to look into it.

**Comment by hsnellen** [comment]
Just checkout out a few: 1094 , 1220, 1303, 152, 216, 257, 306, 378, 425, 489, 512.  All look good.

**Comment by aazaff** [comment]
Agreed with the checks. Next step will be to
- [x] Delete the azlibrary on dev
- [x] Replace tmplibrary as azlibrary on dev

Then we need to rebuild the prod server which is having various hardware problems. We will coordinate that will @snolan1 when @NoisyFlowers  comes in first week of March.
