### ISSUE TITLE
Collection_group descriptions

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#12]
I asked @fmconway to write descriptions for the collections_groups table.

**Comment by aazaff** [comment]
I included these in the latest tmplibrary collection_groups table. @NoisyFlowers can you export that table and add it to your config that information is restored when you recreate the db. I can't get `pg_dump` to work for some reason, presumably because of some complicated credentialing shenanigans.

**Comment by NoisyFlowers** [comment]
The collection_groups in my local vm was up to 24 entries. The one in tmplibrary is at 23. Can you verify that those 23 are the complete set of entries you want to see in that table at this time?

**Comment by aazaff** [comment]
Yes, I removed 1.

**Comment by NoisyFlowers** [comment]
Ok, good deal. Thanks.

**Comment by aazaff** [comment]
Can we close this one?

**Comment by NoisyFlowers** [comment]
There is one that is null: Air photo indexes. Is that expected?

**Comment by aazaff** [comment]
Yes

**Comment by NoisyFlowers** [comment]
Updates to collection_groups in sql schema have been committed.
