### ISSUE TITLE
Upload azgeology newsletters

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#14]
Need to add a new collection_group (azgeology newsletters). Only about 170 items. Should be fairly straightforward for most of them.

- [ ] https://azgeology.azgs.arizona.edu/archived-issues?field_link_title=&items_per_page=All
- [ ] https://azgeology.azgs.arizona.edu/articles/archive?title=&body_summary=&items_per_page=All

**Comment by aazaff** [comment]
Scraping this seems like a hassle. I will try to get into the drupal site instead.

**Comment by hsnellen** [comment]
[Edit]
These few items are distinct from the others in that they are broken down into several different articles. Haley will aggregate them as a single collection with the volume as the title for the metadata and author as null.

- [x] New and Old Fissure Activity in Cochise County, Arizona - https://azgeology.azgs.arizona.edu/archived_issues/www.azgs.az.gov/arizona_geology/spring11/arizonageology.html

- [x] Wildfire, Rain and Floods: A Case Study of the June 2010 Schultz Wildfire, Flagstaff, Arizona - https://azgeology.azgs.arizona.edu/archived_issues/azgs.az.gov/arizona_geology/winter10/arizonageology.html

- [x] Colorado Evolution II - Flagstaff 2010 Workshop: Origin and Evolution of the Colorado River System - https://azgeology.azgs.arizona.edu/archived_issues/azgs.az.gov/arizona_geology/summer10/arizonageology.html

- [x] Glyptodonts in Arizona: A Saga of Supercontinents, Sea Floor Spreading, Savannas, and Sabertooth Cats - 
https://azgeology.azgs.arizona.edu/archived_issues/azgs.az.gov/arizona_geology/spring10/arizonageology.html

- [x] Devil's Kitchen Sinkhole - Sedona, AZ: A Potential Geohazard - https://azgeology.azgs.arizona.edu/archived_issues/azgs.az.gov/arizona_geology/winter09/arizonageology.html

- [x] Holocene Mapping of the San Pedro River System - https://azgeology.azgs.arizona.edu/archived_issues/azgs.az.gov/arizona_geology/summer09/arizonageology.html

- [x] Sunset Crater Volcano (The first digital publication!) - https://azgeology.azgs.arizona.edu/archived_issues/azgs.az.gov/arizona_geology/april09/arizonageology.html

**Comment by aazaff** [comment]
*moved from email*

From @NoisyFlowers 

I imported queue Friday. There were a bunch of errors. I was trying to move the failed directories out of failures into a directory of their own to make it easier to interpret, but ended up botching the bash command and corrupted the directories. I'll have Stephen restore and run the import again. 

Some of the errors I can get rid of before running again by adding the newsletters collection group What should it be called exactly?

From @aazaff 

Arizona Geology Magazine, GMAG? And yeah I forgot to tell you to add that.

**Comment by aazaff** [comment]
I'm going to close this as tentatively complete. We can revisit this again when we do a master inventory once we have a stable production environment.
