### ISSUE TITLE
Purpose of the removed field in uploads table.

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#15]
My original intention for the removed field was that it would be flagged as true whenever a partially completed upload failed and was rolled back.

There seems to be no instance where that field is ever TRUE in the current version of dev.

A few questions:
1. Is there any benefit in using the removed field as I originally intended it, or do you feel the current failure logging is robust enough that this is not needed?
2. Does your code use removed for some other purpose, or is nothing with that field currently implemented?

**Comment by NoisyFlowers** [comment]
uploads.removed is currently unused. See my comment in #16 about possibly moving that to the collections table and tying it in with rollback.

In uploads, however, there may be utility in a field that denotes the status of a failed upload. Possible values could indicate: "pending investigation", "will be corrected and resubmitted", "abandoned". 

Or maybe maintaining that would not be worth the effort. We can always add it later if we decide we like the idea. For now, let's just consider moving the removed field as I mentioned.

**Comment by aazaff** [comment]
No, I don't think a field in uploads is worth maintaining. I'm closing this issue as it is now essentially a duplicate of #16
