### ISSUE TITLE
What are the subdirs azlibConvert and azlibFetch for?

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#17]
azlibAdd and azlibConfigGDB have awesome documentation/readmes!

What are the fetch and convert subdirs for though?

**Comment by NoisyFlowers** [comment]
azlibConvert was for converting the old xml to our json metadata. 

azlibFetch was to provide a command line tool for fetching collections. 

Neither is maintained at this time. Still, I would retain them for posterity. azlibFetch, in particular, could possibly be useful in the future.

**Comment by aazaff** [comment]
That's fine. You can remove them when we start the official 1.1 branch if you want. That way they'll be easy to find again, but it'll clean up the space.
