### ISSUE TITLE
azlibrary errors

### ISSUE THREAD

**Issue by hsnellen** [azgs/azlibrary_database#21]
Was checking out all the azlibrary failures and came across some where I need additional info to correct it.  Error message states: "Syntax Error (43): Illegal character <2e> in hex string\n"
Andrew thinks possible illegal character in PDF? I'll list below the paths with this given message.
"path": "ADMM-1552474465868-194-10000"
"path": "ADMM-1552474295878-10-9961"
"path": "ADMM-1552480403404-36-11204"
"path": "ADMM-1552480781172-887-11348"
"path": "11205"
"path": "11206"
"path": "11207"
"path": "11208"
"path": "11349"
"path": "11350"
"path": "11351"
"path": "11352"
"path": "ADMM-1552433150443-959-1618"
"path": "ADMM-1552433264031-468-1651"
"path": "ADMM-1552433267580-641-1653"
"path": "ADMM-1552433267745-493-1654"
"path": "ADMM-1552433407739-856-1694"
"path": "ADMM-1552433407926-169-1695"
"path": "ADMM-1552434511032-538-1993"
"path": "ADMM-1552434723208-932-2042"
"path": "ADMM-1552434944963-408-2099"
"path": "ADMM-1552436502412-868-2461"
"path": "ADMM-1552436860852-503-2543"
"path": "ADMM-1552437255707-849-2637"
"path": "ADMM-1552438083107-473-2826"
"path": "ADMM-1552438311937-618-2870"
"path": "ADMM-1552438642051-827-2949"
"path": "ADMM-1552438802313-160-2984"
"path": "ADMM-1552439384718-283-3107"
"path": "ADMM-1552442756290-65-3796"
"path": "ADMM-1552444706940-475-4209"
"path": "ADMM-1552447360974-371-4740"
"path": "ADMM-1552447886371-625-4836"
"path": "ADMM-1552459274669-487-7019"
"path": "ADMM-1552462392855-162-7622"
"path": "ADMM-1552468057013-169-8744"
"path": "ADMM-1552467085710-281-8534"
"path": "10542"
"path": "12431"
"path": "12445"
"path": "12458"
"path": "12459"
"path": "12485"
"path": "12815"
"path": "12847"
"path": "13510"
"path": "16967"
"path": "16808"
"path": "16784"
"path": "16502"
"path": "16506"
"path": "16507"
"path": "16504"
"path": "16503"
"path": "16501"
"path": "16499"
"path": "16500"
"path": "16497"
"path": "16498"
"path": "16496"
"path": "16447"
"path": "15909"
"path": "15910"
"path": "15899"
"path": "15685"
"path": "15884"
"path": "15676"
"path": "15427"
"path": "15684"
"path": "15580"
"path": "15426"
"path": "15267"

**Comment by NoisyFlowers** [comment]
First, I want to make sure we're looking at the same things.

Are these errors you are seeing in the failure.json file of collections stored in a failures directory?

The path's you've listed don't look like what I currently generate. I stopped including the perm_id a changeset or so back. From the azlibAdd readme: "If a failure directory is specified, the directories of collections that fail during import are renamed to the upload ID of the import attempt and moved to this directory."

Based on my last imports before I left on vacation, we should only be looking at failures in /azlibrary/failures, /azlibrary/failues-mining-01, and /azlibrary/failures-mining-02.

**Comment by hsnellen** [comment]
I'm opening up the failure.jsons that are stored in the failures-mining-01 and failures-mining-02,
I'll attach an image of what I'm seeing so I can better show you:
![miningfailures](https://user-images.githubusercontent.com/41085615/56524924-1d265400-64ff-11e9-8c61-b52fc0b46ca3.JPG)

**Comment by NoisyFlowers** [comment]
Ah, I see. Ok, FYI: for purposes of communicating the location of a failed collection, that field isn't useful. That refers to the old directory name the collection had in /azlibrary/queue. The useful bit is the uploadID field, as that's what the corresponding directory in failures is called.

You don't have to go back through that list above, but can you point me to one or two directories that have the error you're seeing?

**Comment by hsnellen** [comment]
Oh... thank you! Yeah I had no idea, so this is good to know.
Alright one of them is "10253"

**Comment by NoisyFlowers** [comment]
I found the first one (ADMM-1552474465868-194-10000) in directory /azlibrary/failures-mining-01/10253.

The error dump is a bit nasty to wade through, but note that it says "May not be a PDF file". The file in question is listed as well, in this case "IronMountainYavapai203b.pdf". If you go to the documents directory for this collection and take a peak in the file, sure enough it's actually html, not a pdf. 

I remember thtis now. There are boatloads of these. You can get a list by cd'ing to the failures directory and running 
    grep -r -l "May not be a PDF file" **/failure.json

It might be possible to write a script to extract the name of each errant pdf and rename it to *.html.
