### ISSUE TITLE
Minedata collections that failed upload

### ISSUE THREAD

**Issue by hsnellen** [azgs/azlibrary_database#22]
**failures-mining-1**
- [x] (11891) https://minedata.azgs.arizona.edu/report/pearce-project-platoro-inc

- [ ] (10222) https://minedata.azgs.arizona.edu/report/composite-plan-showing-midnight-shaft-workings

- [ ] (10253) https://minedata.azgs.arizona.edu/report/iron-mountain-0

- [ ] (1504) https://minedata.azgs.arizona.edu/report/letter-reports

- [ ] (1505) https://minedata.azgs.arizona.edu/report/letter-reports

- [ ] (1506) https://minedata.azgs.arizona.edu/report/letter-reports

- [ ] (1507) https://minedata.azgs.arizona.edu/report/letter-reports

- [ ] (1583) https://minedata.azgs.arizona.edu/report/copper-world-mine-0

- [ ] (1582) https://minedata.azgs.arizona.edu/report/copper-world-mine-0

- [ ] (1584) https://minedata.azgs.arizona.edu/report/copper-world-mine-0

- [ ] (1585)  https://minedata.azgs.arizona.edu/report/copper-world-mine-0

- [ ] (2514) https://minedata.azgs.arizona.edu/report/valley-view-claims

- [ ] (2216) https://minedata.azgs.arizona.edu/report/little-favor-group

- [ ] (2215) https://minedata.azgs.arizona.edu/report/little-fanny-ext-group

- [ ] (2175) https://minedata.azgs.arizona.edu/report/light-hall-millsite

- [ ] (2174) https://minedata.azgs.arizona.edu/report/light-claims

- [ ] (2172) https://minedata.azgs.arizona.edu/report/liberty

- [ ] (2139) https://minedata.azgs.arizona.edu/report/lavender-pit

- [ ] (2563) https://minedata.azgs.arizona.edu/report/mission-mine

- [ ] (2620) https://minedata.azgs.arizona.edu/report/morenci-mine

- [ ] (2982) https://minedata.azgs.arizona.edu/report/pinto-valley-mine

- [ ] (3064) https://minedata.azgs.arizona.edu/report/prosperity-mine-group

- [ ] (3158) https://minedata.azgs.arizona.edu/report/red-chief

- [ ] (3391) https://minedata.azgs.arizona.edu/report/santa-claus-prospect

- [ ] (3470) https://minedata.azgs.arizona.edu/report/sheep-mountain-property

- [ ] (3505) https://minedata.azgs.arizona.edu/report/silver-bell-mine

- [ ] (3628) https://minedata.azgs.arizona.edu/report/south-vulture

- [ ] (4317) https://minedata.azgs.arizona.edu/report/abbie-and-ross

- [ ] (4730) https://minedata.azgs.arizona.edu/report/black-cat

- [ ] (5261) https://minedata.azgs.arizona.edu/report/congress

- [ ] (5357) https://minedata.azgs.arizona.edu/report/copper-queen-mine

- [ ] (7438) https://minedata.azgs.arizona.edu/report/property-map-silver-mining-district

- [ ] (8013) https://minedata.azgs.arizona.edu/report/harmony-number-one

- [ ] (8886) https://minedata.azgs.arizona.edu/report/holbrook-potash-deposit

**failures-mining-2**

- [ ] (11891) https://minedata.azgs.arizona.edu/report/pearce-project-platoro-inc

- [ ] (13780) https://minedata.azgs.arizona.edu/report/piedmont-mine-0

- [ ] (13794) https://minedata.azgs.arizona.edu/report/cyprus-mines-corp-pat-hills

- [ ] (13807) https://minedata.azgs.arizona.edu/report/industrial-fuels-corporation-ip-survey-cascabel-area

- [ ] (13808) https://minedata.azgs.arizona.edu/report/johnson-dragoon

- [ ] (13834) https://minedata.azgs.arizona.edu/report/willen-corp-sunizona-1965-maps-ip-survey-notes-and-water-exploration-report

- [ ] (14164) https://minedata.azgs.arizona.edu/report/cattany-and-howe-1964

- [ ] (14196) https://minedata.azgs.arizona.edu/report/kayser-hagen-property-mineral-creek-mining-district

- [ ] (14859) https://minedata.azgs.arizona.edu/report/mammoth-st-anthony

- [ ] (16616) https://minedata.azgs.arizona.edu/report/area-4-aerial-magnetic-location-plan-and-geology

- [ ] (16775) https://minedata.azgs.arizona.edu/report/vulture-ip-traverse-line-no-9

- [ ] (16776) https://minedata.azgs.arizona.edu/report/vulture-ip-traverse-line-no-9-0

- [ ] (16929) https://minedata.azgs.arizona.edu/report/winkler-faulkner-magnetic-susceptibility-log-drill-hole-6-core

- [ ] (17025) https://minedata.azgs.arizona.edu/report/demetrie-wash-ip-survey-percent-frequency-effect-0

- [ ] (17033) https://minedata.azgs.arizona.edu/report/footloose-magnetic-interpretation

- [ ] (17034) https://minedata.azgs.arizona.edu/report/footloose-footloose-project-kalamazoo-claims

- [ ] (17233) https://minedata.azgs.arizona.edu/report/vekol-mine-ip-traverse-line-no-sheet-1

- [ ] (17248) https://minedata.azgs.arizona.edu/report/ash-peak-topos

- [ ] (17258) https://minedata.azgs.arizona.edu/report/preliminary-evaluation-ash-peak-district

- [ ] (17259) https://minedata.azgs.arizona.edu/report/ash-peak-mine-update-canamin-resources-ltd

- [ ] (17851) https://minedata.azgs.arizona.edu/report/boriana-mohave-county-tungsten

- [ ] (17850) https://minedata.azgs.arizona.edu/report/black-warrior-robinson

- [ ] (17849) https://minedata.azgs.arizona.edu/report/black-hawk-group-1

- [ ] (17848) https://minedata.azgs.arizona.edu/report/antler-mohave-county

- [ ] (17847) https://minedata.azgs.arizona.edu/report/angel-danny-ernie

- [ ] (17846) https://minedata.azgs.arizona.edu/report/willow-2-mill-site

- [ ] (17845) https://minedata.azgs.arizona.edu/report/western-armer-1-24-maricopa-county

- [ ] (17796) https://minedata.azgs.arizona.edu/report/gypsum-deposits-southeast-salome-yuma-county

- [ ] (17852) https://minedata.azgs.arizona.edu/report/burro-creek-1

- [ ] (17853) https://minedata.azgs.arizona.edu/report/cod-mohave-county

- [ ] 17854 https://minedata.azgs.arizona.edu/report/cedar-valley-mines-mine-reportassays-1-6

- [ ] 17855 https://minedata.azgs.arizona.edu/report/cedar-valley-mines-production-data-2-6

- [ ] 17856 https://minedata.azgs.arizona.edu/report/cedar-valley-mines-management-proposal-3-6

- [ ] 18133 https://minedata.azgs.arizona.edu/report/sheep-mountain-utah-construction-and-mining-co

- [ ] 18157 https://minedata.azgs.arizona.edu/report/emerald-isle-1

- [ ] 18316 https://minedata.azgs.arizona.edu/report/tyro-0

- [ ] 18709 https://minedata.azgs.arizona.edu/report/zeke-project-land-map-figure-2

**Comment by aazaff** [comment]
@Lbookman Said that she thinks she might be able to find these missing collections.

**Comment by Lbookman** [comment]
@aazaff 19525 and 19524 work

**Comment by aazaff** [comment]
@hsnellen Can you go back and check that you put the correct link for the ones that Laura says are still working?

**Comment by hsnellen** [comment]
Done, I'll be slowly but surely adding more to the list as I go through it.

**Comment by Lbookman** [comment]
11891 should be http://docs.azgs.az.gov/SpecColl/1994-01/1994-01-0045T-1.pdf @hsnellen

**Comment by aazaff** [comment]
I have identified 628 collections that did not make it into the new database. Let's cross-reference this with our list of "failed" collections.

[missing_minefiles.csv.zip](https://github.com/azgs/azlibrary_database/files/3179864/missing_minefiles.csv.zip)

**Comment by aazaff** [comment]
There are 71 collections that Haley listed as failed in this issue, but the csv indicates 628 items...

**Comment by hsnellen** [comment]
Updated csv with a column indicating what was wrong with webpage. 
[missing_mine_files.zip](https://github.com/azgs/azlibrary_database/files/3180168/missing_mine_files.zip)

**Comment by aazaff** [comment]
Okay this latest inventory looks good. What we can do is wait until a production server has been spun up, then go through all the ones where it says "no known problem" and redownload and repackage those.
