### ISSUE TITLE
Files not filled out, collection_id not assigned

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#25]
I opened the azgs.json associated with ADMM-1552441275000-52. I noticed the following mistakes:

1. collection_id is listed as null, but it is in the database as 4020
2. there are three pdfs associated with the collection, but nothing is listed in the files field of the json.
3. its path is listed as /azlibrary/archive-mining/ADMM-1552441275000-52.tar.gz, but its true path is in archive-mining-01

This is not urgent, but I want to put a pin in this for the next time we talk and make sure these are not widespread errors in other collections.

**Comment by aazaff** [comment]
Can confirm this is is also the case with collection 4541 and probably others.

**Comment by aazaff** [comment]
Also, realising now that collection_group_id and collection_id probably shouldn't even be a part of the 
 azgs.json schema are those are purely internal to our database and have no meaning outside of that context.

**Comment by NoisyFlowers** [comment]
Unless I am remembering incorrectly, all of the azgs.json files for the mining sets were created outside of the azlib pipeline. This means that they were not created by azlibConvert. 

azlibConvert does not create collection_group.id and identifiers.collection_id fields. azlibConvert also creates the files list.

azlibAdd refreshes the azgs.json file, but this will only pick up changes made by azlibAdd. In fact, the only fields that azlibAdd actually should be changing ever are identifiers.perm_id (and then only when it was previously null) and identifiers.directory. Everything else should be left alone by azlibAdd or things get circular.

Files is an interesting case though. azlibAdd doesn't use it at all; rather, it walks the directories and processes what it finds. Arguably, azlibAdd could build that as it processes the collection. Perhaps this makes more sense in azlibAdd than in azlibConvert. I'm not sure. Looking at this from the API side, is Files something that would be populated by the interface that creates the azgs.json or something that would be added to azgs.json by the tool that imports the data to the db?

**Comment by aazaff** [comment]
We decided to have the files filed populated by azLibAdd from now on.

**Comment by aazaff** [comment]
Preliminarily addressed the files issue in 8696f9d60865990c1d5ad10d5f6aa8eddbe29d90.

collection_id and collection_group_id can be removed from the metadata files (i.e., azgs.json) through SQL edits to the metadata.metadata table once we switch to a db only build #21

**Comment by aazaff** [comment]
I think this is massively out of date. I don't even know how or when it got fixed (GitHub fail!), but either way I'm closing this.
