### ISSUE TITLE
Go through and decide which unused fields to keep

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#4]
Some fields in collections table are no longer used. We should determine which ones are convenient to keep and which we can drop.

**Comment by aazaff** [comment]
Can definitely drop the publications table and all FKEYS.

**Comment by aazaff** [comment]
ESRI adds a Shape_Length and Shape_Area field by default to its products. I see no reason to keep this pointless information in our db - e.g., ncgmp09.MapUnitPolys. Can keep though if it is a hassle to remove.

**Comment by NoisyFlowers** [comment]
The geodatabase is created in the db from a sql backup of a geodatabase created by GDB import. The idea was that we trim out tables and fields we don't need before the backup. But I see no reason we can't edit that sql backup file directly for something like this. 

I find the Shape_Area field in only one table: MapUnitPolys.

I find Shape_Length in two tables: MapUnitPolys and ContactsAndFaults.

Is this what is expected? Can I delete these fields from both tables they exist in?

**Comment by aazaff** [comment]
Actually… let’s keep them. I realized that they are probably part of the ncgmp09 spec…

**Comment by aazaff** [comment]
I bet we could drop kitchensink_search from metadata.azgs without any fuss!

**Comment by aazaff** [comment]
It seems like I keep suggesting we drop things, but then we realise we should keep them. Let's not even attempt to "clean" these up until we're at project end and we know what is absolutely not needed.

**Comment by aazaff** [comment]
If there is every a v2.0 of this, we shoudl probably just outright merge the metadata.azgs table with the collections table. 

A separate metadata schema was a byproduct of the old ISO XML based system, which we no longer use.

**Comment by aazaff** [comment]
#31

**Comment by NoisyFlowers** [comment]
Public.uploads should be renamed "changes", since it has evolved into a change log for collection admin operations.

**Comment by aazaff** [comment]
This is too big an issue with too many potential side-affects. Let's only remove un-needed fields if/when we find natural opportunities to do so.
