### ISSUE TITLE
What happens to data in the NCGMP09 tables when a collection is removed or superseded?

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#52]
This is just a question. we want to know what the behavior is. There is no "right" answer.

**Comment by aazaff** [comment]
Nothing happens.

**Comment by aazaff** [comment]
What about when there is a patch?

**Comment by NoisyFlowers** [comment]
If the gdb is removed as part of the patch, the records are deleted. Same for ncgmp09 and gems2

**Comment by aazaff** [comment]
Good that is what should happen.
