### ISSUE TITLE
Provide gems import

### ISSUE THREAD

**Issue by NoisyFlowers** [azgs/azlibrary_database#53]
This issue is related to azlibrary_api issue https://github.com/azgs/azlibrary_api/issues/63.

There will be impacts in azlibAdd (particularly in gdb.js) and probably in azlibConfigGDB.

**Comment by aazaff** [comment]
This seems to have superseded #38

**Comment by NoisyFlowers** [comment]
Doh. You're right. I'm close this as a duplicate of #38.
