### ISSUE TITLE
Test script that compares azgs.json to the database?

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#56]
Maybe we should have some periodic script that checks to make sure azgs.json and the database are actually in sync? For example, checking if the private field in the collections table matches the json? 

https://github.com/azgs/azlibrary_api/issues/71

**Comment by NoisyFlowers** [comment]
This is related to #67. One of the solutions proposed there should obviate the need for such a script.

**Comment by aazaff** [comment]
Closed as duplicate of #67
