### ISSUE TITLE
Mixed up collections

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#6]
The backend directories for 

http://repository.azgs.az.gov/uri_gin/azgs/dlio/1664
http://repository.azgs.az.gov/uri_gin/azgs/dlio/1669

Seem to have gotten mixed up. Need to manually go through those directories, validate the content and metadata, and then re-add to the database.

@hsnellen is tagged, but I will need to walk her through how to do this.

**Comment by aazaff** [comment]
merged with #8

**Comment by hsnellen** [comment]
University of Arizona library was used to referenced all existing files were present in folder, as well as all data extracted from AZGS repository.  
New pathway: 
\\BERYL\gis\azgs_reinventoryURLS
