### ISSUE TITLE
Versioning is brittle

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#65]
If collection A is superseded by B and then B is deleted, collection A still says that it is superseded by B. This also makes it impossible to upload a new/correct B.

https://library.azgs.arizona.edu/item/AGDM-1569951333481-110

Related #40

**Comment by NoisyFlowers** [comment]
In this scenario, is B deleted through the API or directly via SQL? 

If the former, we handle that case. Only collections at the end of a superseded chain can be deleted. And it's a soft delete.

If the latter, then why and who did this? Because that's not how you use that.

**Comment by aazaff** [comment]
B is deleted through the API. The issue is A still shows B. 

I think you found the issue - soft delete. Obviously if we keep B around with the possibility of it being restored, then A needs to preserve the relationship to B. Sounds tricky.

**Comment by NoisyFlowers** [comment]
Hmm. Something must have gone off the rails then. We execute the following sql for this purpose during the delete transaction:
```
		update
			public.collections
		set
			superseded_by = null
		where 
			superseded_by = $1
```

I'm going to have to try to reproduce this.

**Comment by aazaff** [comment]
Interesting! I can point to two examples of this in the db with real data. 

A | B
---- | ----
ADGM-1552430342891-875 | ADGM-1655494459900-337
AGDM-1552431769076-690 | AGDM-1569951333481-110

I also found a single reverse case where the A was deleted but B is still around. I know this is definitely prevented under the API logic, but it looks like this case specifically was very old (collection_id = 59) so I bet this is a legacy issue that was somehow grandfathered in before the API logic went live. 

A | B
---- | ----
ADGM-1552430308914-899 | ADGM-1567543591329-501

**Comment by NoisyFlowers** [comment]
Delete transaction logic was added in azgs/azlibrary_api@711edf76d3292b4a6020476b050c6ace9a6bddf1 on January 27, 2020. 

Both of the first two cases are after that date (AGDM-1569951333481-110 on 3/26/2020, ADGM-1655494459900-337 on 6-17-2022).

I could see the -110 case happening if the update was not pushed to prod before 3/26, but the -337 case throws a wrench in that explanation by coming two years later.

**Comment by aazaff** [comment]
Just linking this to its sister issue https://github.com/azgs/azlibrary_api/issues/88
