### ISSUE TITLE
Images works for tiff and jpg, but not PNG

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#72]
Not sure if this is a bug or if we intended to not have png?

**Comment by aazaff** [comment]
I believe this is super easy to fix since we actually keep tables in the db that list what files we specify.

**Comment by NoisyFlowers** [comment]
Ha, that TYPE in the db is a red herring, as it is not used anywhere.

But the fix was still easy. This is in 
azgs/azlibrary_api@11bd09abe82d6f919792b384c00ba7d6115a1676

on ddm-dev, not merged to master but running on prod
