### ISSUE TITLE
Inconsistent Search results

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#74]
https://data.azgs.arizona.edu/api/v1/metadata?title=happy returns no results

And yet, 
````SQL
SELECT count(collection_id) FROM collections WHERE formal_name ILIKE '%happy%'
````

Returns 11 entries in the database. What's the deal?

**Comment by aazaff** [comment]
I'm getting reports of all kinds of borked search behaviours! We will need to commit emergency maintenance.

**Comment by aazaff** [comment]
Some additionally bizarre examples:

Search for "Active" in either Title OR Full-Text 

returns not results but 

`SELECT count(collection_id) FROM collections WHERE formal_name ILIKE '%active%'` has 61(!) hits.

 However we are getting hits for "activ" with no e.

**Comment by NoisyFlowers** [comment]
Everything checks out from the react client through to the sql that is generated and run by the api server. I think the problem is with our tsvector columns.

Ok, so this works:
```
select * from metadata.azgs
where to_tsvector(json_data->>'title') @@ plainto_tsquery('active')

```
This does not:
```
select * from metadata.azgs
where title_search @@ plainto_tsquery('active')

```
The title_search column is built from json_data->>'title'. So, clearly, something is wrong there. Could be and artifact of migrating the db. Could be that our triggers don't work properly in Aurora.

I tried to run this on the Aurora instance:
```
update
      metadata.azgs
set
      json_data = json_data

```
That should trigger all the triggers to run on each row, totally rebuilding the tsvector columns.  However, it was unable to complete:
```
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
CONTEXT:  SQL statement "CREATE TEMP TABLE tabletemp
      (
            json_data jsonb
      ) on commit drop"
PL/pgSQL function metadata.collections_trigger() line 21 at SQL statement

SQL state: 53200
```

max_locks_per_transaction is not something we have control of with Aurora. Can we get somebody to change it for us?

**Comment by aazaff** [comment]
This "triggered" (hah) my memory!

I could probably ask them about changing the max locks BUT I actually remember we've run into this at least twice before on our own server. Unless if we upped the RAM to absurd levels, this query won't work. If I recall correctly, what we ended up doing last time was creating a loop and batching a few thousand at a time.

Does that ring a bell to you. I definitely remember this. I wonder if this is why the move to AuroraDB failed because there was some secret memory balk on the triggers but since the triggers running is not related to the pg_restore it didn't show as a failure. I think once we fix this though we should be good.

What do you think?
________________________________
From: NoisyFlowers ***@***.***>
Sent: Wednesday, February 14, 2024 4:07 PM
To: azgs/azlibrary_database ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>; Author ***@***.***>
Subject: [EXT]Re: [azgs/azlibrary_database] Inconsistent Search results (Issue #74)


External Email

Everything checks out from the react client through to the sql that is generated and run by the api server. I think the problem is with our tsvector columns.

Ok, so this works:

select * from metadata.azgs
where to_tsvector(json_data->>'title') @@ plainto_tsquery('active')



This does not:

select * from metadata.azgs
where title_search @@ plainto_tsquery('active')



The title_search column is built from json_data->>'title'. So, clearly, something is wrong there. Could be and artifact of migrating the db. Could be that our triggers don't work properly in Aurora.

I tried to run this on the Aurora instance:

update
      metadata.azgs
set
      json_data = json_data



That should trigger all the triggers to run on each row, totally rebuilding the tsvector columns. However, it was unable to complete:

ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
CONTEXT:  SQL statement "CREATE TEMP TABLE tabletemp
      (
            json_data jsonb
      ) on commit drop"
PL/pgSQL function metadata.collections_trigger() line 21 at SQL statement

SQL state: 53200


max_locks_per_transaction is not something we have control of with Aurora. Can we get somebody to change it for us?

**Comment by NoisyFlowers** [comment]
I managed to rebuild the tsvector columns in the Aurora db by writing a node script to break the job into multiple update batches of a 100 records each. For posterity, I am pasting the code here.
```
const fs = require("fs-extra");
const dotenv = require ("dotenv");
dotenv.config();

const pgp = require('pg-promise')();

const conn = {
	user: process.env.PG_USERNAME,
	password: process.env.PG_PASSWORD,
	host: process.env.PG_HOST,
	database: process.env.PG_DATABASE,
	port: process.env.PG_PORT,
};

if (process.env.PG_CA_CERT) {
	conn.ssl = {
		rejectUnauthorized: true,
		ca: fs.readFileSync(process.env.PG_CA_CERT).toString(),
	};
}

const db = pgp(conn);

const recordsPerBatch = 100;

const doIt = async () => {
	let maxIdx = 0;
	const maxIdxQ = `
		select
			max(collection_id) as max
		from
			public.collections
	`;
	await db.one(maxIdxQ).then(result => {
		maxIdx = result.max
	});
	console.log(`maxIdx = ${maxIdx}`)

	const loopTerminus = Math.floor((maxIdx + recordsPerBatch)/recordsPerBatch);
	console.log(`loopTerminus = ${loopTerminus}`)

	for (let i = 0; i < loopTerminus ; i++) {
		const startID = recordsPerBatch * i;
		const endID = startID + recordsPerBatch;
		console.log(`${startID} - ${endID}`);
		
		const sqlStr = `
			update 
				metadata.azgs 
			set 
				json_data = json_data
			where
				metadata_id > ${startID} and
				metadata_id <= ${endID}
		`;
		
		await db.none(sqlStr).then(result => {
			console.log(`metadata records ${startID + 1} through ${endID} updated`);
		}).catch(err => {
			console.log(err)
		});
	}
}

doIt();
```

However, this did not fix the problem. In fact, the tsvectors looked identical to the previous.

I'll skip recounting the ensuing research and debugging and jump to the end: I figured out the problem.

When you run to_tsvector and to_tsquery, you can optionally provide a config parameter (https://www.postgresql.org/docs/current/textsearch-configuration.html). If you don't provide this, the system falls back on whatever is configured in the default_text_search_config parameter in postgres.conf.

In the postgresql version we've been running previously, this parameter is set to "pg_catalog.english". In Aurora, it is set to "pg_catalog.simple".

In our triggers, we pass the optional parameter a value of "pg_catalog.english". But in our queries, we omit the optional parameter, so the system falls back on the default. This worked on the old system, but on Aurora, this causes a mismatch between the query and the vector, resulting in weird return values.

The easiest fix would be to change the default value in postgres.conf. But we can't do that with Aurora, so the next easiest is to change our queries to specify the config value to match our triggers. I've done that locally, running the client against the Aurora db, and search behaves properly.  

This is in azgs/azlibrary_api@f08df63a5589a0f929da593ce9d177e2ca4dab4c.

**Comment by NoisyFlowers** [comment]
Deployed to AL2 instance and working there.

**Comment by aazaff** [comment]
I will inquire about getting the conf updated for safety too

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: NoisyFlowers ***@***.***>
Sent: Thursday, February 15, 2024 5:48:01 PM
To: azgs/azlibrary_database ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>; Author ***@***.***>
Subject: [EXT]Re: [azgs/azlibrary_database] Inconsistent Search results (Issue #74)


External Email

Deployed to AL2 instance and working there.

**Comment by aazaff** [comment]
They said that AWS doesn't make that conf editable. So we will just have to be careful in all our queries moving forward.

Putting their official response below.

Greetings Andrew,
We did a little digging into what parameters can be set globally for the AWS implementations of PostgreSQL, and unfortunately it looks like default_text_search_config is not one of them. You can see the full list of globally configurable parameters for PostgreSQL at https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Parameters.html
My best guess for why it's excluded is that they may have determined that setting it incorrectly or with an invalid value would cause the DB to be unstable or to fail to boot. So the AWS developers opted to exclude it to ensure better stability and reliability.
However, it looks like others have run into the same limitation and found alternatives to apply that full text search setting to specific roles and database schemas or to reference it directly in the to_tsvector commands to both set the preferred config and use an additional text search expression index to speed up their searches. See https://stackoverflow.com/questions/40032685/on-aws-rds-postgres-how-to-have-dictionaries-and-unaccented-full-text-search for more details. I'll admit that I'm not familiar enough with full text search via PostgreSQL to be able to test these configuration options. But if you run into problems with testing any of these alternatives, please let me know the details of the problems, and I'd be happy to open a support request with AWS to see if they can provide any additional guidance.
