### ISSUE TITLE
reinventory using URLs

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#8]
The lookup table used in #5 can also be used to inventory any discrepancies between the old document repository and the document repository. It does seem that some collections are missing, for whatever reason.

**Comment by aazaff** [comment]
The following collections are in the current repository, but are not azlibrary.

- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1905
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1239
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1664
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1894
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1895
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1324
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1325
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1326
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1327
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1328
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1329
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1330
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1332
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1333
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1334
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1335
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1336
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1337
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1339
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1340
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1341
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1342
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1343
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1344
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1345
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1346
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1347
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1348
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1349
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1350
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1351
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1352
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1353
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1354
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1355
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1356
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1357
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1358
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1359
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1363
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1364
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1365
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1366
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1367
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1369
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1371
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1372
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1383
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1384
- [ ] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1385
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1900
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1896
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1897
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1898
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1901
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/584
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/594
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1902
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1903
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1904
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/997
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1015
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1027
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1719
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1899
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1692

**Comment by aazaff** [comment]
We need to add https://github.com/azgs/geologic_map_tracking/issues/2 to this list.

**Comment by aazaff** [comment]
Also need to redo

- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1664
- [x] http://repository.azgs.az.gov/uri_gin/azgs/dlio/1669

**Comment by hsnellen** [comment]
University of Arizona library was used to referenced all existing files were present in folder, as well as all data extracted from AZGS repository.
New pathway:
\BERYL\gis\azgs_reinventoryURLS

**Comment by aazaff** [comment]
Let's do this after we finish #22

**Comment by aazaff** [comment]
I'm going to close this issue because we will likely do an entirely new inventory once the production server is complete.

**Comment by aazaff** [comment]
Tuns out it is finally time to take care of these. Interestingly, some of the "checked" ones still are not showing up so I would do them all.

**Comment by aazaff** [comment]
I have identified the following 98! items that are in the Campus Repository but are not in AZLIB. 

I believe that many off them have already been identified elsewhere (either above or in Leah's inventory). We shoudl take some time to cross-reference all the lists of "missing" items into one main list.

[missing.csv](https://github.com/azgs/azlibrary_database/files/10709363/missing.csv)
