### ISSUE TITLE
Deleting user accounts?

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#82]
Is there any danger of something breaking if we delete an entry form the public.users table? Do we track user information from that table in any logs?

**Comment by NoisyFlowers** [comment]
The only foreign key relation to that table that I am aware of is in the uploads table. We can check first to see if the user_id in question has any entries there.

**Comment by aazaff** [comment]
Ah, this is for Haley's old account. So it definitely does. No worries.

**Comment by NoisyFlowers** [comment]
Might need a soft delete function there too.

Or maybe just zap the password field.
