### ISSUE TITLE
How are incomplete azgs.json handled?

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_database#9]
If you got an incomplete azgs.json - i.e., where all of the provided keys and values are valid, but not all keys are included. How does the upload app handle that? Throw an error?

````JSON
{
        "title": "Geologic Map and report of the Cibola Area",
        "authors": [ 
                {"person": "Brian F. Gootee",
                "organization": "Arizona Geological Survey",
                "givenname": "Brian",
                "surname": "Gootee"},
                
                {"person": "Phil Pearthree",
                "organization": "Arizona Geological Survey",
                "givenname": "Phil",
                "surname": "Pearthree"}                          
                ],
        "collection_group": {
                "name": "Digital Geologic Maps"
                }
}
````

**Comment by NoisyFlowers** [comment]
If I reply to these emails, does the Github Issue update automatically?

Collection upload will fail if:

   - There is no azgs.json file
   - The azgs.json contains invalid json syntax
   - The azgs.json file does not contain a complete bounding box

**Comment by aazaff** [comment]
Yes, email replies will automatically update github, but it will send the full header of stuff which is annoying.
